### ISSUE TITLE
Original Chaos is depreciated

### ISSUE THREAD

**Issue by SirBrucey** [Rjevski/aaispy#2]
The original version of chaos is no longer being developed, nor is it supported.
At some point we will be turning it off.

If you are working on a project, I suggest you use chaos2.
URL: https://chaos2.aa.net.uk
Documentation: http://aa.net.uk/pdf/CHAOS2.pdf

**Comment by Rjevski** [comment]
Thanks for the info - I'll update the library as soon as I have more time.

Regards.

**Comment by Rjevski** [comment]
@SirBrucey could I get access to the test API please? I've raised a support ticket #WD16WZ but have yet to receive a reply.

Regards.

**Comment by SirBrucey** [comment]
Hmm you really should have had a reply, sorry about that.
I have taken ownership of the ticket and I will have a look at sorting access when I am next in the office (Monday).

Thanks.

**Comment by Rjevski** [comment]
I've started a [replacement library](https://github.com/Rjevski/chaos2) for the new Chaos.
